# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

setup: &SETUP
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode


development:
  <<: *SETUP
  database: hamster_entries_development
  min_messages: notice

test:
  <<: *SETUP
  database: hamster_entries_test
  min_messages: notice

production:
  <<: *SETUP
  database: hamster_entries_production
